SUPDATA-135,138 improve colour contrast and focus styling
data-govt-nz/rua pull request #131
Opened 2023-06-21 04:07 UTC by catherine-mediasuite

[SUPDATA-135- Keybaorad focus / hover styling ](https://mediasuite.atlassian.net/browse/SUPDATA-135)
[SUPDATA-138- colour contrast](https://mediasuite.atlassian.net/browse/SUPDATA-138)
[SUPDATA-137- Input focus colour](https://mediasuite.atlassian.net/browse/SUPDATA-137)

Description
Makes configuration and secrets mapping simpler by using the envFrom.

There should be 0 change to any of the values as they appear to the website.

2023-06-22 02:28 UTC, jooleearr requested changes
K so it's a bit hard to tell without testing (so please just let me know if I've got this wrong) but I can't see that this has updated the hover colour of the main menu items to a colour that has a sufficient contrast for text that size. 

My understanding of these code changes is that you've updated the 3 problematic theme colours to #019EAD (bondi blue), #4CA22F (green apple) and #E46911 (christine) which will be fine for the icons but does it address the issue shown here: 

![image](https://github.com/data-govt-nz/rua/assets/693082/41576ea6-7bf4-4f3f-a33e-facf1af329e4)

The bondi blue colour for instance would only pass for large text (so bigger than 18px if bold and bigger than 24px if regular weight) but I believe the heading text is only 16px.

All the other issues look good to go - just any text below 18px/bold or 24px/regular using those theme colours that will still fail I think.

2023-06-26 01:20 UTC, catherine-mediasuite commented
I changed the hover colour of the text to be a dark grey instead of theme-colour, the colour is only used for border or background colour. Shall I change so the colours have a 4.5:1 ratio instead?

2023-06-26 02:19 UTC, jooleearr approved these changes

2023-06-28 20:28 UTC, jooleearr approved these changes
Just a question around wrapping values in quotes but looks good apart from that. Again, haven't tested yet but let me know if you'd like me to before it goes through to UAT

2023-06-28 20:28 UTC, jooleearr commented on src/6-information/accordion/_index.scss
> +//           <button class="button-icon size-sm" data-click="dirty; class: state-standard, state-active; trigger: #group-57, #group-57-icon; ariaexpanded: 'true', 'false'; arialabel: See more {$Title
Think I missed this in the other PR but do the arialabel values need to be wrapped in quotes (like the ariaexpanded one)? Or do they behave differently?

2023-06-28 20:28 UTC, jooleearr commented on src/6-information/checklist/_index.scss
> +//       <button class="button-icon" data-click="class: state-standard, state-active;  trigger: #group-1, #group-1-content, #group-1-icon; ariaexpanded: 'true', 'false'; arialabel: Show guidance on q
As above, do the arialabel values need to be wrapped in quotes?

2023-06-28 20:28 UTC, jooleearr commented on src/6-information/checklist/_index.scss
> +//       <button class="button-icon" data-click="class: state-standard, state-active;  trigger: #group-2, #group-2-content, #group-2-icon; ariaexpanded: 'true', 'false'; arialabel: Show guidance on q
Same as above :)

2023-06-28 20:28 UTC, jooleearr commented on src/7-layout/header/_index.scss
> +//       <button class="button-icon navigation-toggle navicon" aria-label="Open menu" data-click="trigger: #site-navigation; class: in-active, is-active; arialabel: Open menu, Close menu">
Same as above :)

2023-06-28 20:28 UTC, jooleearr commented on src/9-plugins/toggler/options/index.js
> +  arialabel,
I know this hurt, but yay for consistency ;)

2023-07-03 22:33 UTC, catherine-mediasuite commented on src/6-information/accordion/_index.scss
> +//           <button class="button-icon size-sm" data-click="dirty; class: state-standard, state-active; trigger: #group-57, #group-57-icon; ariaexpanded: 'true', 'false'; arialabel: See more {$Title
They all come through as strings without the quote marks so I could remove them.

2023-07-04 22:29 UTC, jooleearr approved these changes
Looks good! I'm not sure if they're going to split hairs over this but the top button does cover up a smidge of the legal text at 400% for me still (see screenshot). If that's not an issue then :shipit:

![Screenshot 2023-07-05 at 10 07 13 am](https://github.com/data-govt-nz/rua/assets/693082/039a74db-a274-4cfb-8a1d-d9ccb5eacb0b)

2023-07-04 22:29 UTC, jooleearr commented on src/9-plugins/back-to-top/index.js
> +    console.log(t.scrollTop());
Might just want to remove the console log before this goes to production ;)

2023-07-04 22:29 UTC, jooleearr commented on src/9-plugins/back-to-top/index.js
> +      t.scrollTop() + 150 + t.height() > $(document).height()
150 seems like a bit of a [magic number](https://hireamir.com/blog/software-anti-patterns-magic-numbers). Not a biggie here as the comment above kind of tells the story but can be good practice to assign arbitrary numbers like this to named variables that describe what they are/do :)

2023-07-05 23:32 UTC, catherine-mediasuite commented
I think the button covers minimal content on scrolling up before disappearing so this text can be read. Will leave as is for now.

2023-07-06 00:39 UTC, merged